"""add client_config

Revision ID: 854ae91652ce
Revises: 460c45edfb11
Create Date: 2026-07-03 17:10:06.232066
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854ae91652ce'
down_revision: str | None = '460c45edfb11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'version', name='uq_client_config_version')
    )
    with op.batch_alter_table('client_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_config_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_config_client_id'))

    op.drop_table('client_config')
    # ### end Alembic commands ###
