"""initial schema

Revision ID: 460c45edfb11
Revises: 
Create Date: 2026-07-03 16:59:08.680958
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460c45edfb11'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_inference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('determinism_hash', sa.String(length=128), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('field_reads', sa.Integer(), nullable=False),
    sa.Column('mock_data', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_inference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_inference_run_id'), ['run_id'], unique=False)

    op.create_table('audit_llm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('fell_back', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_llm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_llm_run_id'), ['run_id'], unique=False)

    op.create_table('lineage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('record_scope', sa.Text(), nullable=True),
    sa.Column('principal_id', sa.String(length=64), nullable=True),
    sa.Column('masking', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_run_id'), ['run_id'], unique=False)

    op.create_table('reps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rep_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('territory_id', sa.String(length=64), nullable=True),
    sa.Column('quota', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ote', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('otc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pipeline_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('attainment', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reps_rep_id'), ['rep_id'], unique=True)

    op.create_table('shield_counter',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_type')
    )
    op.create_table('shield_map',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('entity_type', 'original_value', name='uq_shield_entity_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shield_map')
    op.drop_table('shield_counter')
    with op.batch_alter_table('reps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reps_rep_id'))

    op.drop_table('reps')
    with op.batch_alter_table('lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_run_id'))

    op.drop_table('lineage')
    with op.batch_alter_table('audit_llm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_llm_run_id'))

    op.drop_table('audit_llm')
    with op.batch_alter_table('audit_inference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_inference_run_id'))

    op.drop_table('audit_inference')
    # ### end Alembic commands ###
